### ISSUE TITLE
No module named download_with_progress in 4.2.5

### ISSUE THREAD

**Issue by VeyDlin** [blessedcoolant/invoke_meshgraphormer#1]
it doesn't seem to be supported anymore

> Failed to load node pack invoke_meshgraphormer:
> Traceback (most recent call last):
>   File "R:\Apps\InvokeAI\nodes\__init__.py", line 48, in <module>
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "R:\Apps\InvokeAI\nodes\invoke_meshgraphormer\__init__.py", line 1, in <module>
>     from .hand_depth import HandDepthMeshGraphormerProcessor  # noqa F401
>   File "R:\Apps\InvokeAI\nodes\invoke_meshgraphormer\hand_depth.py", line 19, in <module>
>     from .node import MeshGraphormerDetector
>   File "R:\Apps\InvokeAI\nodes\invoke_meshgraphormer\node\__init__.py", line 5, in <module>
>     from invokeai.app.util.download_with_progress import download_with_progress_bar
> ModuleNotFoundError: No module named 'invokeai.app.util.download_with_progress'

**Comment by blessedcoolant** [comment]
Yep. The download API changed. I'll update the extension sometime this week.

**Comment by blessedcoolant** [comment]
Done. You can pull the new changes. The models will redownload but they'll now be controlled by Invoke's cache and download API .. so they'll operate better.

You can delete your previously downloaded models.
